split up ci steps
pondevelopment/actions pull request #4
Opened 2022-06-22 06:46 UTC by apiest-pon

2022-06-22 07:09 UTC, lukepon requested changes

2022-06-22 07:09 UTC, lukepon commented on nodejs/action.yaml
> +      run: |
```yaml
strategy:
      matrix:
        action: ["run vulnerabilities", "lint:report", "test"]
        // ...
steps:
       - name: npm actions
       run: |
          npm ${{matrix.action}}
       env:
            CI: "true"
            NPM_TOKEN: ${{inputs.NPM_REGISTRY_TOKEN}}
```

2022-06-22 07:09 UTC, lukepon commented on nodejs/action.yaml
> +      run: |
you do loose the ability to check on error but we can split the action into an object and do some magic? continue-on-error doesnt work in `composite` actions (maybe now?)

```yaml
strategy:
      matrix:
        action: [{"op":"run vulnerabilities", "error": true}, {"op":"lint:report", "error": false}, {"op":"test", "error":false}]
        // ...
steps:
       - name: npm actions
       run: |
          npm ${{matrix.action.op}}
       env:
            CI: "true"
            NPM_TOKEN: ${{inputs.NPM_REGISTRY_TOKEN}}
         continue-on-error: ${{matrix.action.error}}
```

2022-10-03 17:47 UTC, pieter-pon approved these changes
Better than it was! 👍

2022-10-28 21:16 UTC, merged